- shell_fish.go
- test/direnv-test.fish
- test/direnv-test.sh
- test/scenarios/dump/.envrc
After I submitted #156 I found that other characters are incorrectly escaped for `fish` too - specifically the '*' character.
Rather than explicitly escaping special characters, this patch just wraps exported values in single quotes, only breaking out for special non-printable characters (\t, \xxx, etc). This makes the logic much simpler, and it now works properly when variables contain spaces and `*` (and perhaps others that I haven't encountered yet).
There's also a new test case, `dump`, which tests both fish & bash on a bunch of special characters, as well as covering #157 (so it'll fail until that it merged as well).
> shell_fish: use single quotes to simplify escaping logic

- env_diff.go
The following .envrc:
direnv_load env VAR=new bash -l -c "direnv dump"
When loaded from a shell that _isn't_ bash (e.g `fish`), gives me:
/usr/bin/bash: line 167: export: `BASH_FUNC_scl()=() {  local CMD=$1;
if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
eval "module $@";
else
/usr/bin/scl "$@";
fi
}': not a valid identifier
/usr/bin/bash: line 167: export: `BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}': not a valid identifier
This is because bash exports some whacky variables (for inheriting functions) when it's run as a login shell (these functions come from somewhere in /etc/profile.d). But `direnv apply_dump` generates invalid bash syntax when it hits these variable names. Since it's impossible to export variables with these names in bash, and no other shell is …
> ignore BASH_FUNC_* variables

- shell_vim.go
`unlet $FOO` throws `E488: Trailing characters` error and there
is no way to unload environment variable in Vim
(see http://permalink.gmane.org/gmane.editors.vim.devel/44555).
Instead, just make it empty string (which is not the desired
effect but is the best possible solution)
Related to zimbatm/direnv.vim#2.
> Empty variable as unloading in Vim

- stdlib.go
- stdlib.sh
- test/direnv-test.sh
- test/scenarios/missing-file-source-env/.envrc
`source_env ..` fails if `../.envrc` doesn't exist. I'm not convinced it should. What are your thoughts on this?
TL;DR
My use-case is a top-level dir which contains multiple apps, each with their specific `.envrc`. I store common values in the top-level dir which is not version-controlled. This global `.envrc` might not exist on all workstations. Currently, direnv fails:
```
/bin/bash: line 134: ./.envrc: No such file or directory
direnv: error exit status 1
```
I would much rather it gracefully handled the absence of `../.envrc`
> Direnv should not fail if ../.envrc doesn't exist

- env_diff.go
I have problems using a modified SHELLOPTS with cygwin and zsh.
When I go to any .envrc folder this VAR is modified and is added to direnv managed vars.
Example:
➜  git $  echo $SHELLOPTS
igncr
➜  git $ cd xxxx
direnv: loading C:\Users\xxxxx\Documents\git\xxxx\.envrc
direnv: loading .envrc.mine
direnv: loading .envrc.xxxx-xxxx
direnv: export +SPARQL_REPOSITORY_URL ~SHELLOPTS
➜  xxxx git:(develop) ✗ $ echo $SHELLOPTS
braceexpand:errexit:hashall:igncr:interactive-comments
➜  xxxx git:(develop) ✗ $ cd ..
direnv: unloading
➜  git  $ echo $SHELLOPTS
igncr
Consider add this variable to ignored vars list
> Added SHELLOPTS to ignored vars

- stdlib.go
- stdlib.sh
This lets users easily add [`nix`](http://nixos.org/nix/) expressions to their direnv environment, either by explicitly specifying packages:
use nix -p python3 ocaml
..or by relying on the default `nix-shell` behaviour when you have a `default.nix` or `shell.nix` in the current directory:
use nix
(This all relies on `nix` being installed, of course).
> Add use_nix() helper to stdlib

- man/direnv.1
- man/direnv.1.md
Nitpick fix: lintian threw this warning when building the direnv package for debian.
> Fix lintian spelling warning

- shell_zsh.go
Hi all,
After installed direnv 2.7.0 through Homebrew, I added `eval $(direnv hook zsh)` to my `.zshrc`, but the hook didn't work. And there are my findings.
The following element existence checking expresion:
$precmd_functions[(r)_direnv_hook]
will be treated as following by ZSH interpreter:
${precmd_functions}[(r)_direnv_hook]
hence:
[[ -z $precmd_functions[(r)_direnv_hook] ]] == [[ -z "[(r)_direnv_hook]" ]] == false
That's why this change is made. With this patch, `eval $(direnv hook zsh)` works perfectly in my shell (ZSH v5.0.5). Anyways, I have to say thanks to you to create such an awesome tool for us!
- Raphanus
> Eliminate syntax ambiguity in zsh hooking script

- man/direnv-stdlib.1.md
- stdlib.sh
- `use node` Loads NodeJS version from a `.node-version` or `.nvmrc` file.
- `use node <version>` Loads specified NodeJS version.
- requires environment variable $NODE_VERSIONS
- optional environment variable $NODE_VERSION_PREFIX
> Add `use node` directive to stdlib

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
If you specify a partial NodeJS version (i.e. `4.2`), a fuzzy match is performed and the highest matching version installed is selected.
> Add fuzzy matching to `use node` stdlib function

- README.md
Help gentoo users to install it without google
> added reference to gentoo go-overlay to readme

- README.md
This was something that I overlooked which lead to me having [an issue](https://github.com/direnv/direnv/issues/199).
So I tried to add something to the `README.md` to try to make it clearer that the `.envrc` must use valid bash syntax.
https://github.com/msabramo/direnv/blob/README_add_caveat_that_envrc_must_be_valid_bash_syntax/README.md
Fixes: GH-199
> README.md: Caveat that .envrc must be valid bash

- cmd_prune.go
- commands.go
- rc.go
The problem:
When we enable reading  .envrc with  `direnv allow` command, we create empty file in .config/direnv/allow/, but when we remove entrie directory with .envrc, "allow hash" still exists.
Solution:
I add code to store path to .envrc in "allow-hash" file, and implement `prune` subcommand, which remove stalled files from .config/direnv/allow (old empty files still be untouched)
> Add ability to prune references to .envrc, which no more exists

- cmd_hook.go
- cmd_watch.go
- env.go
- env_diff.go
- shell.go
- shell_bash.go
- shell_fish.go
- shell_json.go
- shell_tcsh.go
- shell_test.go
- shell_vim.go
- shell_zsh.go
A new export format that makes it easier to integrate direnv with IDEs.
The IDE has to call `direnv export json`.
If the exit status > 0 display the output and abort.
Parse the JSON, the format is `{"key": value}` where the value is either a string or null. If the string is null unset the env, otherwise set it.
> Export JSON

- stdlib.go
- stdlib.sh
I use [n](https://github.com/tj/n) (It's very famous node.js manager). It install node.js to non-prefixed directory.
```
% ls n/versions/node
0.10.36  0.12.12  4.3.2  5.7.1  6.2.0
```
direnv can change node.js search prefix via the `NODE_VERSION_PREFIX` variable, but can't accept  empty string. The PR is fixed it.
> Permit empty NODE_VERSION_PREFIX variable

- Makefile
- config.go
- main.go
This change allows to hard-code the bash path into direnv at compile
time. This avoiding a lookup on the $PATH on every evaluation of direnv.
To do this run `make BASH_PATH=$(readlink -f $(which bash))`.
There is no measurable difference on a SSD.
/cc @pwaller 
This is going to be useful in nix packaging to provide bash path as an immutable build dependency.
> Build-time bash path

- shell_tcsh.go
prevent a final $ in a variable value from causing a tcsh error
> fix tcsh escaping

- stdlib.sh
If `$MANPATH` is empty, `man` still knows where to look.
If `$MANPATH` is not empty, `man` will only look in those paths.
Instead of setting `MANPATH=$dir` in `path_add`, prepend `$dir` to the default MANPATH-equivalent calculated with `man -w`.
For Darwin, see "SEARCH PATH FOR MANUAL PAGES" section of [`man man`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/man.1.html).
For Linux, see [`man 5 manpath`](http://man7.org/linux/man-pages/man5/manpath.5.html).
Fixes #247.
> When MANPATH is empty, prepend to a default value in path_add

- stdlib.go
- stdlib.sh
Introduce the `$direnv_layout_dir` variable to let the user select
out-of-folder layouts. The main purpose of making this configurable is
to allow the user to store the `.direnv` folder outside of the
project's directory. For example if it interracts badly with backups,
source control or the IDE.
The variable can be changed in the `.envrc` file or in the global
`~/.config/direnv/direnvrc` file. In that case on might want to hash the
project path like that:
```
: ${XDG_CACHE_HOME:=$HOME/.cache}
pwd_hash=$(echo -n $PWD | shasum | cut -d ' ' -f 1)
direnv_layout_dir=$XDG_CACHE_HOME/direnv/layouts/$pwd_hash
```
> stdlib: configurable direnv_layout_dir

- stdlib.go
- stdlib.sh
If you use -P you get the absolute "physical" path removing any
symlinks, however it is then used in a context where it is expecting a
relative path to find the .envrc file. As a result, it can often be
incorrect and cause `pushd` errors.
Fixes GH#294
> pwd: Don't use -P to remove symlinks

- stdlib.go
- stdlib.sh
This fixes an issue where the first .envrc fixes the $direnv_layout_dir
in combination with source_up or source_env.
Fixes #297
> stdlib: make direnv_layout_dir lazy

- stdlib.sh
This adds a new layout, similar to `layout_python`, but uses Pipenv to build the virtualenv from the Pipfile located in the same directory.
> Add support for Pipenv layout

- .travis.yml
- cmd_stdlib.go
- stdlib.go
- stdlib.sh
direnv tests fails when built from sources with golang-1.10. This was
reported in debian bug #890852.
The failure seems to be caused by incorrect escaping of '%' in 'direnv
stdlib'. Fix this by not using printf.
Add build test for go 1.10
Fixes #338
> fix support for go 1.10

- config.go
- man/direnv.toml.1
- man/direnv.toml.1.md
- rc.go
the `.envrc` shouldn't be interactive as it can be loaded from tooling
Fixes #350
> config: allow to disable stdin on eval

- README.md
This is far more useful than source_env (so much that possibly it should be default)
> Add the usage of source_up to the README

- .gitignore
- stdlib.go
- stdlib.sh
Adds handling of `PIPENV_PIPFILE` environment variable,
allowing this:
```bash
export PIPENV_PIPFILE="${PWD}/app/Pipfile"
layout_pipenv
```
instead of this:
```bash
cd "${PWD}/app"
layout_pipenv
cd -
```
> handle `$PIPENV_PIPFILE`

- README.md
- get-direnv
Curl installer is supposed to ease deployment by automating
all install steps.
This first version will build the code but in the future
we may want to add option for binary install.
> adds experimental curl based installer

- shell_bash.go
If the original PROMPT_COMMAND ends with semicolon, the extra one will cause
bash script throw "syntax error" because of double semicolon in the
PROMPT_COMMAND.
> Avoid to add unnecessary trailing semicolon character

- man/direnv.1
- man/direnv.1.md
It was not clear from the current documentation that `.envrc` can not only add variables via `export` but can also remove them via `unset`.
> Document possibility to unset vars

- cmd_show_dump.go
- commands.go
This is a private command used to debug when things go wrong. It can
decode and print the content of a DIRENV_DIFF or the output of `direnv
dump`.
Used to debug #394
> direnv show_dump: new command to debug encoded env

- README.md
Add packaging status from repology. This gives a better idea if your
favourite distribution has it.
[Rendered view](https://github.com/zimbatm/direnv/tree/readme-packaging-status/#from-system-packages)
> README: add packaging status badge

- README.md
Nowadays it's just "openSUSE". The upper and lower-case version of SuSe isn't used anymore.
> Correctes spelling of openSUSE

- cmd_dump.go
- cmd_show_dump.go
- env.go
- env_diff.go
- file_times.go
- gzenv/gzenv.go
- shell.go
- shell_bash.go
- shell_elvish.go
- shell_fish.go
- shell_gzenv.go
- shell_json.go
- shell_tcsh.go
- shell_vim.go
- shell_zsh.go
This is useful in scenarios where an environment is cached between runs
Fixes some of #405 . Only for commands with a --pure option similar to nix-shell.
> add optional "bash" argument to `direnv dump`

- GNUmakefile
On Windows, generate the direnv executable with the .exe file extension
> make: generate direnv.exe on windows

- file_times.go
- test/direnv-test.bash
- test/scenarios/symlink-changed/.envrc
- test/scenarios/symlink-changed/.gitignore
- test/scenarios/symlink-changed/state-A
- test/scenarios/symlink-changed/state-B
Stat only looks at the target of symlinks, and Lstat
examines the symlink itself.
This change allows changes to both the symlink and
the symlink's target to trigger updates.
> file_times: use Lstat as well as Stat

- file_times.go
- test/direnv-test.bash
Only trigger a reload if either Stat or Lstat don't match the expected
time exactly.
Before this patch, if direnv was watching a symlink, direnv always
thought the file was stale, because the Lstat didn't match the Stat
results.
> file_times: check Stat and Lstat

- README.md
Changed the nix link to go directly to the package description.
> Doc: change nixos link

- cmd_exec.go
The cleaned-up environment created after reverse patching the current environment was not used for the exec cmd.
> Corrects reverse patching when using exec cmd.

- shell_bash.go
When the direnv is the first element added to PROMPT_COMMAND
(PROMPT_COMMAND is empty) the trailing semicolon character is unneeded,
and, in some cases, breaks the prompt due an invalid syntax when more
elements are added.
> Fix bash hook

- README.md
This PR drops a repeated build badge.
- this was also in PNG not readable SVG
> README: Remove duplicate build badge

- shell_elvish.go
this also remove `echo $e` which is annoying when there is no .envrc in current or parent folders
> fix arity mismatch error

- azure-pipelines.yml
- cmd_allow.go
- cmd_apply_dump.go
- cmd_current.go
- cmd_deny.go
- cmd_dotenv.go
- cmd_dump.go
- cmd_edit.go
- cmd_exec.go
- cmd_expand_path.go
- cmd_export.go
- cmd_help.go
- cmd_hook.go
- cmd_prune.go
- cmd_reload.go
- cmd_show_dump.go
- cmd_status.go
- cmd_stdlib.go
- cmd_version.go
- cmd_watch.go
- commands.go
- config.go
- man/direnv.toml.1
- man/direnv.toml.1.md
timeouts are only applied on cmd_export
this sets the duration after which direnv should warn the user that
configuring direnv from environment variables should be deprecated
> config: direnv warn timeout

- cmd_exec.go
```
$ direnv exec bash -c "true"
direnv: error stat bash: no such file or directory
$ direnv exec bash
direnv: error stat bash: no such file or directory
```
Meaning leaving out the DIR argument was never really an option.
> direnv exec: DIR is always necessary

- config.go
- man/direnv.toml.1.md
it was confusing that the man page and configuration name weren't the
same. Keep config.toml around for back-compate.
see also https://github.com/direnv/direnv/issues/180#issuecomment-494287848
> rename the configuration to direnv.toml

- stdlib.go
- stdlib.sh
Fixes `layout_pipenv`'s check for a venv path. For some reason, the error from `pipenv --bare --venv` when the venv doesn't exist does not exit the script in bash 5.0 (brew), but does in bash 3.2 (macos stock). Perhaps there needs to be some follow up investigation on if `set -e` is being enforced properly for bash 5.0.
This also removes an extra `pipenv --venv` lookup when it's already created, which will be every time except possibly the first, which should speed up loading a bit.
Resolves direnv/direnv#500
> Handle failing pipenv on missing venv and avoid an extra pipenv execution

- shell_fish.go
This is more reliable, as `fish_prompt` could miss changing directories with Alt+Left/Right. It also runs when pressing enter on an empty shell, so as far as I can tell it's a superset of `fish_prompt`.
The preexec event was added to fish in https://github.com/fish-shell/fish-shell/pull/1666, which was after this line was last touched :) By now, even Debian should have a recent-enough fish to support this.
> Use `fish_preexec` event instead of `fish_prompt`

- shell_zsh.go
Prepend but not append `_direnv_hook` to make sure environment variables are changed before any other hooks, in case the vars are used by other hooks. This is what bash does with `PROMPT_COMMAND` in `shell_bash.go`.
Besides, add `_direnv_hook` into `chpwd` hook, which is triggered once working dir is changed by ZLE widget but not command `cd` in ZSH.
> shell: improve zsh hook

- .gitignore
- stdlib.go
- stdlib.sh
This is a follow-on to #429, rebased on master, with a couple updates:
* Only invoke python once to determine the Python version and whether venv is available (since invoking the python interpreter is relatively slow)
* Explicitly check for the existence of virtualenv (since it's not part of the standard library)
* Use pkgutil instead of import to check for the availability of venv and virtualenv so we don't output a multiline traceback to stderr if an import fails*
* Don't export VIRTUAL_ENV if neither venv nor virtualenv are available (for folks who set PS1 with the value of VIRTUAL_ENV to indicate that a virtual environment has been successfully activated, this would otherwise be quite misleading)
This PR also adds `/test/scenarios/inherited/.envrc` to .gitignore, which is generated by …
> stdlib: venv and pyenv

- CHANGELOG.md
- cmd_watch.go
- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
The rationale is that when watching a large number of files it can take a noticeable amount of time to add all the watches.
This also removes the code that replaces leading tildes with `$HOME` on the filename passed to watch_file. A leading tilde is typically replaced by the shell. By doing it a second time it complicates watching files that do actually begin with a tilde. But I'm happy to put it back in (and make it work for multiple files) if removing it is a blocker.
> Watch more than one file at a time.

- nix/sources.json
I suspect that people are now switching from 19.03 to 19.09. This change just means there's less to download when running `nix-shell` in the project directory initially because the diff between one's own system and the pinned version is smaller.
> Pin nixpkgs to current NixOS 19.09 channel

- docs/ruby.md
change link to stdlib from `/stdlib.html` to `/man/direnv-stdlib.1.md`
Closes #532
> docs: fix invalid link

- README.md
[asdf-direnv](https://github.com/asdf-community/asdf-direnv) is an [asdf](https://asdf-vm.com) plugin for integration between asdf and direnv.
> Add link to asdf-direnv.

- shell_fish.go
Using `fish_preexec` causes Direnv to 'detect' and source the `.envrc` with 1 prompt of lag when changing directories with `cd`. Because the `fish_preexec` seems to be executed before the new directory is entered. 
https://asciinema.org/a/jl7G5qNPNZ0qAVRoTFHHiOMXH
https://github.com/fish-shell/fish-shell/issues/6465
> Use `fish_postexec` to make sure direnv hook executed 'after' the directory has changed when using `cd`.

- shell_elvish.go
TODO: for elvish 0.12+ we should check for `$nil`
> shell: fix elvish hook

- cmd_dump.go
- stdlib.go
- stdlib.sh
- test/scenarios/dump/.envrc
Fixes issues where that error message would appear (#519)  :
direnv: error unmarshal() base64 decoding: illegal base64 data at input byte 0
The issue was that `direnv_load` was reading from the sub-command
stdout, which could also containt content from other commands than
`direnv dump`. This is now solved by opening a fifo pipe between the
load and the dump function.
> stdlib: direnv_load can now handle stdout outputs

- main.go
Short version: forcibly unset `$PWD` to unbreak .envrc access.
Unix "current working directory" at the kernel level is always the absolute path (the process state tracks the VFS node, roughly).
Given this directory, file, and symlink:
~/foo/src/github.com/example/work-repo/
~/foo/.envrc
~/foo/quick -> src/github.com/example/work-repo
then after `cd ~/foo/quick` the fact that "quick" was used is not in the kernel state.  The shell knows it, so that it can handle `cd ..` specially (instead of accessing the VFS's `..` entry).  POSIX specifies handling for `$PWD` (but doesn't require that the shell export it). Typically, bash/zsh do export `$PWD`.  If, within `~/foo/quick/` you run `bash -c pwd; env PWD= bash -c pwd` then you can see how `$PWD` controls "what is the current directory".
The …
> bug-fix paths when PWD has a symlink in it

- .github/workflows/go.yml
- GNUmakefile
- stdlib.go
- stdlib.sh
- test/stdlib.bash
Adds a "test suite" for the stdlib and fix some of the unused variables issues that appeared after setting `set -u` in 2.21.0
> stdlib unused variables pass

- config.go
`direnv.toml` was not read since `config.TomlPath` was overwritten.
> config: fix the configuration file selection

- config.go
TOML will look at the underlying representation and find the integer,
then try to parse an integer instead of the time.Duration.
> config: fix warn_timeout parsing

- config.go
- man/direnv.toml.1
- man/direnv.toml.1.md
- rc.go
When set to true, the `.envrc` will be loaded with the `set -euo
pipefail` flags.
> config: add strict_env option

- stdlib.go
- stdlib.sh
- test/scenarios/dump/.envrc
Fixes #569.
Previously a call to, for example, `direnv_load true` would cause direnv to hang. This is because the command didn't include a call to `direnv dump`, hence nothing ever wrote to the far end of the named pipe that had been created to receive the output from the given command, `true`.
Another example:
```
direnv_load bash -c 'do_something_that_breaks && direnv dump'
```
In this instance we've rememebered to call `direnv dump`, but it is never called because `do_something_that_breaks` returns non-zero.
> Simplify direnv_load and make it work even when the command crashes.

- stdlib.sh
The stdlib of direnv uses the environment variable XDG_CONFIG_DIR
instead of XDG_CONFIG_HOME to determine the location of the user defined
configuration directory.
Fixes #595
> stdlib: fix direnv_config_dir usage

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
- test/stdlib.bash
When working on a machine with a managed development environment, it's common for the managed `PATH` to have many entries. `PATH_rm` allows me to selectively remove entries that conflict with specific projects.
Example:
echo $PATH
PATH_rm '/opt/my_employer/*'
echo $PATH
> stdlib: add PATH_rm <pattern> [<pattern> ...]

- man/direnv-stdlib.1.md
I noticed that I have `layout php` in one project and `layout_php` in another and wondered what is the canonical one that should be used.
looked up in documentation and did notice `layout php` missing:
- https://direnv.net/man/direnv-stdlib.1.html#codelayout-lttypegtcode
> direnv-stdlib.1: add layout php

- stdlib.sh
Update `layout go` so that the layout dir is added to GOPATH instead of PWD.
Since go does not want to see `go.mod` in GOPATH, PWD is not available sometimes.
> stdlib: `layout go` adds layout dir to GOPATH

- docs/hook.md
For some reason, the Fish example was rendering with a ">" at the beginning, even though ">" wasn't present in the code itself. This is invalid, no ">" is needed. I changed the backtick language from `fish` to `sh` like the others, and it seemed to stop rendering a ">".
> Remove ">" typo in Fish hook instructions

- cmd_hook.go
Without this fix, you have to write your own `_direnv_hook` to run on Cygwin or msys/git bash, because the backslashes are currently interpreted as escapes within the string, rather than actual characters.
(Technically, all the Hook functions should be escaping `.SelfPath` in their templates, but that's a *much* bigger change since most of the shell implementations don't have an escape method, and doing the escaping internal to the Hook method means changing a lot of files.)
> Make `direnv hook` output work on Windows

- stdlib.go
- stdlib.sh
I didn't remove the fd# support from cmd_dump, but it's not needed any more.
(I'd like to also get rid of `DIRENV_DUMPFILE_PATH`, as it seems like a bug magnet.  But with fd's not working on Windows, I'm not sure what I'd replace it *with*.)
> Fix #594 - write error to fd 3 on Windows

- cmd_exec.go
- cmd_export.go
- config.go
- rc.go
The previous logic flow for export was highly non-linear and tightly state-coupled across multiple functions with side-effects, making it extremely hard to follow what was happening.
This refactoring linearizes the core logic of export, replacing struct members with simple local variables, and makes all the internal functions fully functional and side-effect free.  In addition, some duplicated high-level code and miscellaneous housekeeping from exec and export was moved into rc and config, further clarifying how both exec and export work.
You can now see how the various env values are reverted, diffed, patched, etc. in one screenful of code, without needing to search through multiple functions trying to figure out who was doing what to whom in which order.  This should make it easier to …
> Streamline core algorithm of export and exec

- cmd_allow.go
It was incorrect in the output when migrating direnv data.
Fixes #640
> Change XDG_CONFIG_DIR to XDG_CONFIG_HOME

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
Note: This is pending https://github.com/direnv/direnv/pull/665 which I factored out from this branch to simplify reviewing.
`stdlib`: new function `use_julia` that loads the specified julia version. The implementation is similar to `use_node`. In particular it requires the user to specify the directory with installations with `$JULIA_VERSIONS` and for partial versions a `semver_search` is performed.
Edit: 1cfc446a9a6e9cc18d448a8167524e841f98e787 is the commit to review for this PR, the rest are autogenerated changes or changes to review in https://github.com/direnv/direnv/pull/665.
> stdlib: use_julia <version>

- stdlib.go
- stdlib.sh
- test/stdlib.bash
The first commit fixes some complaints when running with `-u` as is done in the tests:
```
stdlib.sh:354: !1: unbound variable
```
and
```
stdlib.sh:359: path_array[@]: unbound variable
```
The fix for the array expansion is taken from https://stackoverflow.com/a/61551944/5087136 which suggests this fix as the "only safe idiom". I am not 100% sure about this first commit, so please review carefully!
The second commit is just a stupid bug fix -- the empty version prefix should of course be used, just like https://github.com/direnv/direnv/blob/98033c305ef2fdd3eb7ad5a83974c24da8becd15/stdlib.sh#L861. Also adds tests to `use julia` (which is what prompted the first commit, since `path_add` errors otherwise).
> stdlib/use_julia: fix a bug in parameter substitution

- man/direnv.toml.1.md
From the documentation it wasn't quite clear where the `direnv.toml` was
being sourced from.
> Clarify path to direnv.toml

- stdlib.go
- stdlib.sh
When `set -u` is being used, Bash 3.0 tracks empty array as unused
variables.
There is a big table of compatible versions, with each their own errors:
https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u/61551944#61551944
Thanks to @fredrikekre for finding the root cause.
Fixes #675
> stdlib: use Bash 3.0-compatible array expansion

- man/direnv.toml.1
- stdlib.go
- stdlib.sh
Closes #677 
This updates the `stdlib` to look for `direnvrc` and `lib/*.sh` in
`$DIRENV_CONFIG` first, then `$XDG_CONFIG_DATA/direnv`, and finally
`$HOME/.config/direnv`.
Few notes:
* I forgot to run `make` in #678 
* The `XDG_CONFIG_DATA` bit is not mentioned in the README (though `$HOME/.config` is) so I haven't documented the `$DIRENV_CONFIG` mechanism either. Happy to amend.
> Look for stdlib in DIRENV_CONFIG

- shell_elvish.go
https://elv.sh/blog/0.14.0-release-notes.html
I haven't manually tested this on Elvish 0.12 but was at least able to confirm that the `all` builtin exists in that version.
Without this change, opening a new shell results in a deprecation warning like the following:
```
deprecation: the "explode" command is deprecated; use "all" instead
/Users/USERNAME/.elvish/lib/direnv.elv, line 6: 			m = (explode $m)
```
> shell: Update Elvish hook to replace deprecated `explode`

- man/direnv-fetchurl.1
- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
Provide an easy way to extend the stdlib with scripts from the Internet.
While still enforcing some level of security.
Eg:
source_url "https://raw.githubusercontent.com/nmattia/sorri/bff9e44734b19d5c65534c9bfd10bdf3be90b623/sorri" "sha256-CMbjOcSXWtTqSW0jKBPWWPBMBiOvJsh2vnFJoQJ6yFM="
To find out the hash, get the immutable script URL, then run `direnv fetchurl <url>` to get back the hash.
> stdlib: add source_url function

- cmd_exec.go
Currently, when running `direnv exec <dir> <command>`, the environment is not restored unless there is a `.envrc` file in or above `<dir>`. This PR ensures that the environment is also restored when no `.envrc` file is present in or above `<dir>`.
See #383 for a test case. Assuming that there is no `.envrc` in `~` or `~/tmp`, without this PR:
```
~/tmp/foo❯ direnv exec .. ../check
FOO: foo
BAR:
~/tmp/foo❯ direnv exec ../bar ../check
FOO:
BAR: bar
```
The expected output occurs when `<dir>` is `../bar`, because `../bar` contains a `.envrc`. However, when `<dir>` is `..`, where there is no `.envrc`, the environment is not properly restored.
With this PR:
```
~/tmp/foo❯ direnv exec .. ../check
FOO:
BAR:
~/tmp/foo❯ direnv exec ../bar ../check
FOO:
BAR: bar
```
resolves #383
> fix: use restored env in exec

- cmd_allow.go
At least on macOS, paths passed to `direnv allow <dir>` weren't being fully resolved during the `allow` process. For example, `direnv allow /tmp/dir` would store an authorization for /tmp/dir/.envrc. On Macs, /tmp is an alias for /private/tmp, and when the user actually cd-ed into /tmp/dir, the path provided by os.Getwd would be /private/tmp/dir, which resulted in a different hash.
Aliases aren't symlinks, but go's `EvalSymlinks` resolves them anyway.
Both the `Abs` and `EvalSymlinks` calls are required, as `Abs` doesn't resolve links and `EvalSymlinks` doesn't resolve relative paths.
resolves #694
> fix: handle links on Mac when using `allow`

- rc.go
Some broken filesystems like SSHFS return file information on stat() but
then cannot open the file. So we use os.Open instead.
Fixes #704
> rc: make file existence check more robust

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
- test/stdlib.bash
This allows to shorten a common pattern:
source_env_if_exists .envrc.private
> stdlib: add source_env_if_exists

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
I want to load `.vimrc.local` stored on the project top dir every time Vim runs `direnv` command. There is a similar solution already on [Wiki][wiki], but this has some problems.
[wiki]: https://github.com/direnv/direnv/wiki/Vim
This solution expects `direnv` sets env variables before Vim starts to open files. Vim starts, then it reads `$EXTRA_VIM` in sourcing `~/.vimrc`, and loads the local `.vimrc`.
But with this, Vim cannot load the local `.vimrc` in the following cases.
1. When another `DirChanged` event occurs. (that is, `direnv` command runs again)
2. When another buffer window opens.
- This is needed because the local vimrc's often set buffer-specified settings. (`setlocal`, `b:foo_var`, and so on)
To solve this, Vim should source the local `.vimrc`'s just after `direnv` command …
> Add use_vim to source local vimrc

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
- test/stdlib.bash
- test/strict_env_test.bash
Allows the gradual introduction of `set -euo pipefail` into envrc processing,
as discussed in #566, as well as an escape hatch for commands that must be run
in the envrc context that do not meet `set -euo pipefail` requirements.
> Add strict_env and unstrict_env

- stdlib.sh
Tests are passing under Linux/Ubuntu as far as I could see. 
Resolves #707
> Fix proposal for  #707, broken direnv compatibility under Windows

- stdlib.go
- stdlib.sh
Similar to `layout_pyenv`, this relies on the existence of `nodenv` and its `versions` directory, e.g. `$(nodenv root)/versions`.
Unlike `layout_pyenv`, this takes only one argument and adds a single version to the `PATH`.
> Added use_nodenv to stdlib

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
- test/stdlib.bash
This is a `strict_env`-friendly version of `dotenv`
for .env files which may not exist,
e.g. in the case of a boilerplate .envrc used in many places
to optionally load .env files if present.
Fixes https://github.com/direnv/direnv/issues/728.
> Add `dotenv_if_exists`

- man/direnv.1
- man/direnv.1.md
- shell_fish.go
closes #583 
I updated the `fish hook` to handle the 3 use cases that @pjeby mentioned through an environment variable
```fish
set -g direnv_fish_mode eval_on_arrow    # trigger direnv at prompt, and on every arrow-based directory change (default)
set -g direnv_fish_mode eval_after_arrow # trigger direnv at prompt, and only after arrow-based directory changes before executing command
set -g direnv_fish_mode disable_arrow    # trigger direnv at prompt only, this is similar functionality to the original behavior
```
The `disable_arrow` option is similar to the original functionality with no support for the arrow directory change.  However, the hook is on `fish_prompt` instead of `fish_postexec` which for most use cases should provide the same functionality.
Also, update the docs to use …
> updated fish hook support issue

- GNUmakefile
- default.nix
- docs/hook.md
If you are maintaining a direnv package, your packaging instructions
will have to change.
Rename DESTDIR to PREFIX. Semantically, PREFIX is used to declare where
the files will live on the file-system after installation and DESTDIR is
a temporary location used during packaging. This commit fixes that
semantic.
Distribute the fish hook with the package. These can be removed from the
packaging instructions now.
> packaging: change DESTDIR to PREFIX

- README.md
I think at this point it's not obvious that Nix-direnv is the absolute best way
to integrate Direnv with Nix.  Nix-direnv is certainly the best option for Nix
Flake support.  But for integration with Nix-shell, I think there can be valid
reasons to recommend some other approaches.
Rather than load the README with a long list of Nix integration projects (I'm
sure Direnv is used by a lot more people than Nix users), I tried to improve the
[Nix wiki page](https://github.com/direnv/direnv/wiki/Nix) to better explain the
trade-offs of different approaches so users could make a more informed decision.
So this commit just changes the pointer to Nix-direnv to point to the Nix wiki
page instead.  I just want to avoid pointing users to one project over another
when there's not one singularly best …
> Relax README's recommendation for nix-direnv

- GNUmakefile
- cmd_fetchurl.go
- cmd_show_dump.go
- config.go
- default.nix
- docs/development.md
- env.go
- env_diff.go
- file_times.go
- go.mod
- shell_gzenv.go
Fix the usage of Go modules so that `go get` actually installs the
latest version.
Bump the minimal Go version requirement to 1.15.
Fixes #629 and #762
> go: use the /v2 prefix

- docs/development.md
The `GNUmakefile` uses the `PREFIX=/usr/local` for the install, so it should be replaced and not the `DESTDIR`.
> Change DESTDIR to PREFIX in development.md

- cmd_export.go
- cmd_watch_dir.go
- cmd_watch_list.go
- config.go
- gzenv/gzenv.go
- nix/sources.json
- script/str2go.go
- test/direnv-test.elv
In recent versions of elvish the builtin path-dir has been moved to a
module. Update the test script to use the module to avoid a warning
about deprecated usage. The move of "path" to the module also seems to
have updated the key "path" to "name" - reflect this in the test
script.
Similarly, temporary assignment now requires using the "set"
keyword. Fix this while at it.
> test: Fix errors for elvish test

- .github/workflows/go.yml
- .github/workflows/release.yml
- GNUmakefile
- docs/development.md
- go.mod
- Bumps Go up to 1.16
- Adds `darwin/arm64` to the list of architectures to build against
Resolves #738
> Go 1.16 and Apple Silicon support

- rc.go
As there is no movement on a more specific PS1 warning (as suggested in https://github.com/direnv/direnv/issues/618), and there is light support for removing it completely via "thumbs up", putting up this PR for discussion.
As discussed there, it seems to me this warning slipped in due to probably an abundance of PS1 complaints at that time, which should be fixed now that the issue is amply documented. There are likely many other things that "don't work" and could be warned about, so at least from my perspective, there's a wavy line between warning "just in case", vs. the noise this produces, at least in every Python virtualenv-based use case (which can be silenced with `unset PS1`, but...).
> Remove noisy warning about PS1 again

- shell_bash.go
- shell_tcsh.go
PR 788 (https://github.com/direnv/direnv/pull/778) to fix  #769 introduced extra quotes around lower case characters.  This PR should fix that issue.  Also, fixed a const misnomer 'LOWERCASE_Z', ascii 90 is uppercase `Z`.
> Fixed extra quotes for lower alpha characters

- stdlib.go
- stdlib.sh
I've found it to be very helpful to be able to match a regexp rather than an exact GitHub branch. In my use case, I do this to choose between a Python 2 layout vs Python 3, for example (included in documentation):
```bash
if on_git_branch -r '.*py2'; then
layout python2
else
layout python
fi
```
> Add -r flag for matching Git branches with a regexp

- shell_zsh.go
closes #803 
The issue is when something like `set -e` or `set -euo pipefail` is set, it causes the conditional check to fail and then the entire script for the hook exits.
This updates the conditional so that it doesn't error out in this scenario. It's adapted from the POSIX-compliant test here:
https://stackoverflow.com/questions/42655304/how-do-i-check-if-a-variable-is-set-in-zsh
> Updated conditional for zsh hook to be more forgiving

- docs/installation.md
macports and homebrew now point to the actual direnv page, as opposed to the homepage for the respective package managers
> docs(install): fix macos links

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
I noticed some projects in the wild calling `use_flake` without sourcing
the `use_flake` function. It's time to add this to the stdlib.
> stdlib: add use_flake function

- stdlib.sh
Nix doesn't automatically create the folder if it doesn't exist, so we
have to do it ourselves.
Fixes #860
> stdlib: use_flake handle no layout dir

- install.sh
I can't run `curl -sfL https://direnv.net/install.sh | bash` on macOS with Apple Silicon
```
[installer] Machine arm64 not supported by the installer.\n Go to https://direnv for alternate installation methods.
[installer] the script failed with error 1.\n \n To report installation errors, submit an issue to\n     https://github.com/direnv/direnv/issues/new/choose
```
But, direnv supported Apple Silicon https://github.com/direnv/direnv/pull/779
I was able to install it with this modified script.
> update installer for Apple Silicon

- rc.go
- test/direnv-test.bash
It turns out that os.Open can also open folders. In Unix, everything is a file.
Fixes #863
> rc: ignore .envrc and .env if they are not files

- main.go
This fixes the version command showing an extra newline:
```
$ direnv version
2.30.1
$ 
```
And fixes #867.
> Strip newline from version.txt

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.sh
- test/stdlib.bash
Check presence of env vars:
env_vars_required SOME_TOKEN
Fixes #843
> stdlib: add `env_vars_required`

- internal/cmd/cmd_exec.go
- internal/cmd/cmd_export.go
- internal/cmd/config.go
- internal/cmd/rc.go
- man/direnv.toml.1
- man/direnv.toml.1.md
- test/direnv-test-common.sh
- test/scenarios/skip-env/.env
The feature to automatically load .env files in https://github.com/direnv/direnv/pull/845 is nice, but it's a little too greedy in certain situations. Allow skipping that behavior by default (going back to explicit `dotenv` calls in `.envrc` files) in the configuration toml file.
> Allow skipping `.env` autoload

- internal/cmd/config.go
I was looking through [`config.go`](https://github.com/direnv/direnv/blob/f68f741895754e9551059c8e0132a796ad1c3c3a/internal/cmd/config.go), and I found a comment that was incomplete. It turned out that the final line was accidentally deleted in #573.
I can't find any development guide on things like commit message conventions or PR workflow, so I hope I am doing this correctly. Please let me know if I need to change anything.
> Re-add accidentally deleted comment line

- docs/installation.md
The link to the arch-aur-package is dead, as this package is now available in the official repo.
> doc: fix the broken link to arch linux

- internal/cmd/cmd_exec.go
- internal/cmd/cmd_export.go
- internal/cmd/config.go
- internal/cmd/rc.go
- man/direnv-stdlib.1
- man/direnv.toml.1
- man/direnv.toml.1.md
- test/direnv-test-common.sh
Loading the `.env` files is a change in behaviour and broke
backward-compatibility. It sounds really nice at first but it turns out
that many users have .env files littered in their repository and cause a
direnv reload. It's possible to turn that feature off but now they have
one extra step to instruct their users.
This commit inverts the behaviour and turns that feature off by default
to restore back-compat.
See also #878.
> Don't load .env files by default

- docs/installation.md
The old apps.fedoraproject.org is no more! Update the Fedora package link to point to the new location for the direnv package.
> installation.md: Fix Fedora package link

- stdlib.sh
- test/stdlib.bash
Paths passed to `source_env(_if_exists)` are logged as-is, e.g. `.envrc.local`.
This PR ensures the full path is logged, like with `source_up`.
```bash
$ cat foo/.envrc
source_up
source_env .envrc.local
$ direnv exec foo true
direnv: loading ~/src/direnv/foo/.envrc
direnv: loading ~/src/direnv/.envrc
direnv: loading .envrc.local
$ direnv exec foo true
direnv: loading ~/src/direnv/foo/.envrc
direnv: loading ~/src/direnv/.envrc
direnv: loading ~/src/direnv/foo/.envrc.local
```
> source_env: show full path

- man/direnv.1
- man/direnv.1.md
- man/direnv.toml.1
- man/direnv.toml.1.md
> man: clarify paths

- man/direnv-stdlib.1
- stdlib.sh
This fixes https://github.com/direnv/direnv/issues/913
While I was in here, I opted to make the existing `source_up` script log
explicitly when it can't find a file. I think that's useful both with
strict_env enabled and disabled.
> source_up_if_exists: A strict_env compatible version of source_up

- internal/cmd/shell_vim.go
ref: `:h setenv()` https://vimhelp.org/builtin.txt.html#setenv%28%29
Of note, the `:h expr-env` documentation says
> The functions getenv() and setenv() can also be used and work for
> environment variables with non-alphanumeric names.
> The function environ() can be used to get a Dict with all environment
> variables.
> Use setenv in vim to allow non alphanumeric vars

- stdlib.sh
Currently an error is encountered if an environment name is not
specified to `layout anaconda`. This change attempts to detect
the environment name from the environment.yml file by grepping
for the `name` property and processing the result.
The result is that .envrc files can now simply contain
`layout anaconda` as long as the local environment.yml
file specifies a `name`.
No new dependencies are introduced as `grep` is already used
and additional processing is performed using Bash parameter
expansion.
> feat: allow conda environment names to be detected from environment.yml

- stdlib.sh
tput is not portable.
See https://github.com/dylanaraps/pure-bash-bible#escape-sequences
> stdlib.sh: remove dependency on tput

- internal/cmd/cmd_stdlib.go
- internal/cmd/rc.go
- internal/cmd/stdlib.go
Reduce the amount of commits to land with the gosh branch.
- stdlib: factor out stdlib preparation
- rc: install interrupt handler earlier
- rc: prepare stdin earlier
- rc: stop using --noprofile --norc
> gosh-related refactors

- internal/cmd/config.go
Expand a path string prefixed with ~/ to the current user's home directory.
Example: if current user is `user1` with home directory in `/home/user1`,
then `~/project` -> `/home/user1/project`
It's useful to allow paths with `~/`,  so that `direnv.toml` can be reused via
dotfiles repos across systems with different standard home paths
(compare Linux `/home` and macOS `/Users`).
Feedback is welcome e.g. if/how this should be tested. For now manual
testing of prefix & exact has been done confirming that full paths as
well as `~/`-paths works.
I looked here for how to expand tilde:
https://gist.github.com/miguelmota/9ab72c5e342f833123c0b5cfd5aca468
I also found a third party module that expands tilde
https://github.com/prep/tilde
that we can swap in instead of the `expandTildePath` method in …
> Expand `~/` in whitelist paths

- CHANGELOG.md
- internal/cmd/cmd_allow.go
- internal/cmd/cmd_deny.go
- internal/cmd/cmd_help.go
- test/direnv-test-common.sh
- test/scenarios/aliases/.envrc
It's easy to forget the correct command name -- so support them all!
- allow  / block
- permit / deny
- grant  / revoke
Closes #832
> Add convenient aliases for allow/deny commands

- .github/workflows/go.yml
- .github/workflows/nix.yml
- .github/workflows/release.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- README.md
- internal/cmd/cmd_allow.go
- internal/cmd/cmd_deny.go
- man/direnv.toml.1
- man/direnv.toml.1.md
Follow-up on direnv#845 and direnv#911: resolves direnv#916
This commit simply updates the error messages and documentation to more
accurately reflect the current opt-in configurable handling of `.env` files.
> Clarify handling of .env files

- internal/cmd/cmd_fetchurl.go
If I understand the docs properly, it should follow 30x redirects. We
don't want error responses, and things like 201 are also not interesting
to us.
Fixes #886
> fetchurl: only store 200 responses

- default.nix
- go.mod
- go.sum
This is a new architecture being introduced in go1.19 (golang/go#46229); it's a desktop/server architecture, so there are going to be direnv users. (Me included; hence this patch.)
BTW thanks for the great project!
> go: bump golang.org/x/sys for linux/loong64 support

- stdlib.sh
Test if stderr is a tty before sending escape codes
Fixes #953
> stdlib: only use ANSI escape on TTY

- stdlib.sh
Conda assumes the environment config is provided by
environment.yml when the --file argument is not
provided. This allows for specifying a path to
a different file. For example, a project that has
a two environment definitions based on host platform.
Some of the projects I work with don't use environment.yml
in the root directory. I've been using this in my direnvrc to
handle it.
> Update layout anaconda to accept a path to a yml file

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
It appears to me that `layout pyenv` is not mentioned in the stdlib manpage.
Also sync omissions to `man/direnv-stdlib.1.md` from manual changes to `man/direnv-stdlib.1` (https://github.com/direnv/direnv/pull/921).
> Add stdlib pyenv docs

- internal/cmd/rc.go
- test/direnv-test-common.sh
- test/scenarios/$test/.envrc
If a path would include $, it was getting expanded during the
evaluation.
Reported by Fabian Thorand
> fix path escaping

- internal/cmd/shell_elvish.go
https://elv.sh/blog/0.18.0-release-notes.html#deprecated-features
fix #902 
related #914
> elvish: replace deprecated `except` with `catch`

- test/show-direnv-diff.sh
Hello
Coreutils' `base64` program has no `-D` flag (uppercase) to decode data : https://man.archlinux.org/man/base64.1
Thanks
> fix(test): use lowercase -d flag for base64 decoding of DIRENV_DIFF

- stdlib.sh
There's not much point in keeping separate virtualenvs for different patchlevels from the same Python release branch.
> stdlib/layout_python: exclude patchlevel from $python_version

- internal/cmd/rc.go
Seems slightly more performant (unsure if measurable in practice) and cleaner this way.
> Stat the already open rc file rather than another path based one on it

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- stdlib.sh
This patch switches the use_guix behavior to the new version of guix environment, which became the new supported method to spawn on-the-fly environments since the 1.4.0 Guix release.
> stdlib: use_guix: Switch to guix shell.

- internal/cmd/cmd_allow.go
- internal/cmd/cmd_deny.go
- internal/cmd/cmd_dotenv.go
- internal/cmd/cmd_fetchurl.go
- internal/cmd/cmd_hook.go
- internal/cmd/cmd_prune.go
- internal/cmd/cmd_show_dump.go
- internal/cmd/commands.go
- internal/cmd/config.go
- internal/cmd/file_times.go
Fixes issues preventing golangci-lint from passing. Following this `golangci-lint run` and `make test` (which calls into golangci-lint) should not fail at the lint step.
- Change unused argument names to `_`.
- Add toml and json tags to a couple of structs that are serialized as toml and json respectively.
> Fix golangci-lint issues

- GNUmakefile
Firstly, thank you for this excellent tool!
I've built this from source successfully.
Skipping some tests (fish, zsh, etc. don't exist for IBM Z) in order to get `make test` to run cleanly for this platform.
> Skip some tests for IBM Z mainframe's z/OS operating system

- docs/installation.md
direnv [has been packaged for winget](https://github.com/microsoft/winget-pkgs/pull/106059) which allows to install it from binariees on Windows with `winget install direnv.direnv`:
I've successfully used `direnv` in Git Bash on Windows 11:
UPDATE: There are quirks on Windows. It works, unless initials of path names together with Windows path separator make one of C-escape codes e.g. `\t` or `\a`
> Add Windows installation with winget

- internal/cmd/rc.go
- test/direnv-test-common.sh
- test/scenarios/special-characters/backspace/return/.envrc
https://github.com/direnv/direnv/pull/975 had the unintended consequence of causing the `RC::Load` call to sometimes fail when running under git-bash (and some others Windows specific configs).
The `RC::Load` -> `cmd.Output()` calls end up interpreting characters like \b or \t as escape sequences, which is problematic for paths like 'myProject\buckets\test'.
This patch addresses this by forcing the use of `/` as a separator, even on Windows. This works fine in my testing in git-bash. This shouldn't impact systems where `/` is already in use.
This also adds a test case that covers the behaviour being adjusted. In order to run the bash tests on Windows, I had to disable a number that appear to not play nice -- but after hacking those out I was able to verify the new test case.
Fixes:
- …
> Fix incorrect escape sequences during Loads under git-bash

- docs/installation.md
Archlinux has migrate their repos from svn to git and merge the community repo into the extra one in the process. This commit fix the broken link.
> (docs) Fix broken links in installation.md

- shell.nix
- stdlib.sh
- test/direnv-test-common.sh
This allows backup software to skip this directory for backups
> stdlib: create CACHEDIR.TAG inside .direnv

- stdlib.sh
Without this change, when source_env loads a file from subdirectory the subdirectory is duplicated in the printed path. For example, if `~/tmp/.envrc` contains:
source_env subdir
direnv prints:
direnv: loading ~/tmp/subdir/subdir/.envrc
Fixes #1143
> Print correct path in source_env log message

- install.sh
Hello,
the machine=arm is known under several uname -m's.
I have added 2 fixes:
1) armv7l -> arm
2) in the part where the download url is found, both arm64 and arm is found for machine=arm so I added an end of line anchor to the grep.
2) can have unforeseen consequences if other machines expect a loose match instead of a rigid match.
> add support for armv7l platform in install.sh

- docs/installation.md
Changed NixOS installation URL to the options search instead of the direnv package
> update NixOS installation instructions

- internal/cmd/config.go
- internal/cmd/rc.go
Currently if an `Allow` check fails direnv will prompt the user to `direnv allow` the file.  However, `direnv` will do that even if the user explicitly ran a `direnv deny` command, which is not necessarily the desired behavior.
In particular, a user might have `direnv` installed and enabled but might not wish to enable the `.envrc` file for every repository that they interact with.  However, currently `direnv` will always prompt the user to `direnv allow` every time they `cd` into a repository with a `.envrc` file.
This fixes that by recording when the user explicitly denied a `.envrc` file so that `direnv` knows not to prompt again.
There is one key difference between how `direnv allow` and `direnv deny` record the hash.  `direnv allow` records a grant based on the file's (name × …
> Don't prompt to allow if user explicitly denied

- internal/cmd/commands.go
From the Go specification:
> "1. For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/ZkGmict4Iqj
> Remove redundant nil check in `CommandsDispatch`

- internal/cmd/cmd_deny.go
- test/direnv-test-common.sh
I don't often have to turn direnv off, so I haven't been able to learn that it's `direnv deny` or `direnv revoke`. Instead I always find myself trying to run `direnv disallow` since it's the direct inverse of `direnv allow` in my head.
> feat: alias `direnv disallow` to deny

- man/direnv.toml.1.md
This is a followup to issue #926 which requested support for
tilde -> $HOME expansion in the [whitelist] section of direnv.toml.
> direnv.toml.1.md: add examples for $HOME expansion

- internal/cmd/shell_bash.go
Since Bash 5.1, the PROMPT_COMMAND variable can be an array.
Fixes #1199
> fix: support Bash 5.1 array PROMPT_COMMAND

- stdlib.sh
Before this, layout python or layout pyenv would always output the following:
`DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead`
> Update stdlib.sh to avoid deprecation warning

- internal/cmd/cmd_export.go
- internal/cmd/cmd_help.go
- internal/cmd/cmd_prune.go
- internal/cmd/cmd_reload.go
- internal/cmd/cmd_status.go
- internal/cmd/shell.go
This PR comes from https://github.com/direnv/direnv/pull/1226#issuecomment-1891682072
Moving away from `direnv export` as a private function means we should document it in `direnv help`.
> Added `export` function in `direnv help`

- stdlib.sh
I was compiling julia master and it errored out and after talking
to the julia devs they say it is becaues LD_LIBRARY_PATH is set
and it should never be set (julia takes care of it automatically).
So since no upside in setting it and only a downside, submitting
a PR.
> Fix: `use_julia` should not set LD_LIBRARY_PATH

- stdlib.sh
In line with [this helpfully compiled information on usage of .node-version files' suggested compatible format of .node-version files](https://github.com/shadowspawn/node-version-usage#suggested-compatible-format), it would be helpful for direnv to strip off leading `v` prefixes of a version specifier for broader compatability.
> stdlib: use_node: strip leading v from version

- docs/hook.md
The plugin is a bit easier to configure, and what oh-my-zsh users are more used to.
> Add shell setup instructions for oh-my-zsh

- internal/cmd/shell_zsh.go
* Semicolon not needed at end of command.
* `[@]` not needed if variable is not within `""`. Anyway, the quotes would only serve to expand empty-string entries in the array, which should not exist here.
* Simplify test for occurence of `_direnv_hook` in array. This syntax also works with what was previously reported in #803:
$ set -euo pipefail
$ typeset -ag precmd_functions
$ print $precmd_functions
$ print ${precmd_functions[(I)_direnv_hook]}
0
$ print "${precmd_functions[(r)_direnv_hook]+1}"
$ print ${precmd_functions[(r)_direnv_hook]}
zsh: precmd_functions[(r)_direnv_hook]: parameter not set
> Update zsh syntax in internal/cmd/shell_zsh.go

- stdlib.sh
Note: Unless there's consensus that this is a good idea, let's talk about it. I've just noticed these things eating up my disk space without manual intervention, and it seemed annoying. And I thought a PR is a nicer discussion base than a feature request.
(I also haven't actually run the code yet :scream:  I'll get to that in the next days)
---
This is a pretty significant change for people who care about this, but I'd argue that this is very rarely the case.
The two reasons I can see why one would like to keep an old generation are
1. Enable rollbacks
2. Prevent garbage collection
Given that use_flake is always used with a flake.nix file and most probably in a version controlled project, reverting flake.nix seems like an easier way to roll back than fiddling with generations (which would …
> stdlib: use_flake: don't keep old generations around

- internal/cmd/shell_bash.go
Not that this would be performance critical, but in principle.
Also makes the match test more exact, rather than hitting anything with a `_direnv_hook` substring.
> Avoid use of regex in bash hook output

- internal/cmd/cmd_dotenv.go
This change introduces PWD support to the `dotenv` functionality, so that it can resolve PWD in `.env` files.
When .env is loaded, PWD will be set to the same folder that .env file can be found in variable can be used.
A user would also expect that the PWD variable is matching the folder that the .env file resides in, and symlinks should not interfere with that either.
Fixes #1051
> Fix using PWD in .env files

- internal/cmd/cmd_edit.go
given EDITOR not set by the user, use editor set by the system administrator.
> direnv edit: editor when EDITOR not found, closes #1246

- stdlib.sh
Since python 3.12 was released, `layout python` produces the following warning: `<string>:1: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead`. This commit resolves the warning by using the suggested alternative.
Issues: This will break `layout python2` and `layout python3` for versions before 3.4.
> stdlib: update layout_python to resolve deprecation warning

- README.md
Hey!
Just a small update to README.md
On first look, I think that direnv isn't support NuShell :(
This patch will exclude such missunderstanding
> add NuShell into list of supported shells

- stdlib.sh
This ensures that new binaries are installed into project-specific directories instead of the global one (if set). Since it only affects **the installation of new binaries** (using `go install`), it does not conflict with existing setups.
> stdlib: export GOBIN for layout_go

- test/direnv-test.mx
Fixed typos in python-layout test in direnv-test.mx identified [here](https://github.com/direnv/direnv/pull/1291)
Apparently I was pinged about this a couple of weeks ago, but I only got a notification today -- sorry for any inconvenience!
> test: Fix Murex python-layout test

- stdlib.sh
Tools that use flake feature should enable the necessary flags. This is best practice in the nix tooling ecosystem introduced by nixos-rebuild.
> stdlib: enable flakes when use flake is used

- GNUmakefile
- docs/hook.md
- man/direnv.1
- man/direnv.1.md
The elvish install instruction use a deprecated (since 0.16) location for elvish modules.
I also needed a different command to install the command to generate the man page.
> Update elvish docs

- man/direnv.toml.1
- man/direnv.toml.1.md
Added version information (`direnv >= 2.31.0 is required`) for the `load_dotenv` option in the direnv documentation, addressing the confusion and concerns raised in #1100 and potentially helping with issues like #1189.
Version requirement was determined from PR #911, which introduced this feature.
> docs: Add version requirement for load_dotenv option

- .gitignore
It's useful to have `use flake` in `.envrc` while working on this repo, but then one needs to manually remember not to accidentally commit it, since it was intentionally removed in a0c7fd44ea3d865b75f508fdff8e1bb08d27d866. This PR just adds `.envrc` to the `.gitignore`, but uses a leading slash to ensure that it's only ignored at the repo root.
> Add `.envrc` to `.gitignore`

- internal/cmd/config.go
- internal/cmd/rc.go
This just indicates that there is no configuration for the current directory; it doesn't need to generate logging.
Fixes https://github.com/direnv/direnv/issues/455
> Don't give an error when the current directory doesn't exist

- install.sh
When running in a CI environment we sometimes experience rate limiting from the GitHub API when trying to run direnv's install.sh. This causes the whole build to fail, which can be frustrating.
The Homebrew project has previously worked around a similar issue by allowing the user to optionally authenticate using their personal GitHub account, which results in a higher rate limit on API usage. (See `HOMEBREW_GITHU_API_TOKEN` docs here: https://docs.brew.sh/Manpage).
This PR introduces a similar optional environment variable for direnv's install.sh script, which will allow us to inject a dedicated authentication token into our CI builds and avoid spurious failures.
I wasn't sure if you'd want a note added in `docs/installation.md` - please just let me know if you would and I'll add it.
The …
> optionally authenticate against github api during install

- man/direnv.toml.1
- man/direnv.toml.1.md
These new configuration fields were recently introduced in #1336 and will be included in the next minor version (presumably v2.36.0).
This makes it clearer that these options aren't available in older released versions.
The annotation format is the same as what is used for 'load_dotenv'.
> docs: note direnv version for log_{format,filter}

- stdlib.sh
direnv uses temp directory variables that are not valid after the exit of nix-shell. nix-shell cleans up these environment variables.
> use_nix: unset TMPDIR variables

- stdlib.sh
The fix merged by #1176 cleans up the deprecation warning, but breaks for all python versions prior to 3.4.  This change uses some simple try/except blocks to successively look for `venv` or `virtualenv` without version checking or conditional imports:
```python
import platform as p
try:
import venv
ve="venv"
except Exception:
try:
import virtualenv
ve="virtualenv"
except Exception:
ve=""
print(p.python_version()+" "+ve)
```
> A more universal fix for the python 3.14 `find_spec` deprecation warning

- stdlib.sh
This is roughly a copy of https://github.com/flox/flox-direnv - tagging its contributors: @rossturk @bryanhonof @dcarley lmk if this looks good to you or if you're opposed to bringing `use_flox` here.
> Add `use_flox` to stdlib.sh

- stdlib.sh
https://github.com/direnv/direnv/pull/1409 added code to restore special envvars (yay), but it was inside the check which only happens when there are no arguments.
Moving the code block up means this works in cases like `use nix -p go`, not only `use nix`.
> use_nix: always restore special variables

- man/direnv-stdlib.1.md
the original link leads to a 404 page.
> doc: fix link to guix manual

- internal/cmd/mod.go
Fixes a regression in #1336, which caused error messages to display poorly (or in some cases not at all). See the linked issues.
Fixes #1425
Fixes #1431
Also deletes a duplicate ansi escape code.
> add trailing newline to error messages

- internal/cmd/cmd_export.go
Fixes a regression introduced by cf9222e.
At this point in the control flow, `err` is non-nil if there was an error in config.EnvFromRC. We depend on it remaining non-nil until the return statement. cf9222e inadvertently unconditionally overwrote `err`, causing this function to never report errors from config.EnvFromRC. Fixed by giving the new error a different name.
You can test the issue by editing this repo's .envrc file and then running `go run . export bash`.
Fixes #1463
> fix regression in displaying export errors

- internal/cmd/config.go
Treat the `-` value of the `log_format` option specially to match the [documented behavior](https://github.com/direnv/direnv/blob/v2.37.1/man/direnv.toml.1.md#log_format).
Fixes #1419
> Disable status logging with `log_format = "-"`

- internal/cmd/cmd_help.go
This is one potential solution to #1452
Rather than displaying aliases as individual commands, it groups them under the appropriate command.
I personally feel like an additional newline between each command could be nicer to read, but didn't want to make extra changes.
Previous output:
```
Available commands
------------------
allow [PATH_TO_RC]:
permit [PATH_TO_RC]:
grant [PATH_TO_RC]:
Grants direnv permission to load the given .envrc or .env file.
block [PATH_TO_RC]:
deny [PATH_TO_RC]:
disallow [PATH_TO_RC]:
revoke [PATH_TO_RC]:
Revokes the authorization of a given .envrc or .env file.
```
Adjusted output:
```
Available commands
------------------
allow [PATH_TO_RC]:
aliases: permit, grant
Grants direnv permission to load the given .envrc or .env file.
block [PATH_TO_RC]:
aliases: deny, …
```
> make it clear which commands are aliases in help output
