direnv/direnv

- env_diff.go
- stdlib.go
- stdlib.sh
Various cleanup, mostly the stdlib to use more features of bash. I am a bit worried of having regressions.
> Misc cleanup

- shell_bash.go
Credit to @sykesm for reporting in detail.
Fixes #155
> Preserve previous BASH status code

- stdlib.go
- stdlib.sh
This also adds the support of the new watch capabilities to the .env files.
/cc @nyarly
> Watch dotenv

- README.md
To fix some typos and to reword in a few places for clarity or grammar.
> Fix some typos and reword in a few places

- README.md
- man/direnv-stdlib.1.md
- stdlib.sh
I've been using both the direnv package from GNU Guix, and the `use guix` helper that @zimbatm wrote for me for many months now. Its been working really well, and I haven't heard about any issues, so please consider adding it to the stdlib :)
> Add `use guix` and update README to mention GNU Guix

- stdlib.sh
Allows useful `layout_python3 --system-site-packages`
> Pass additional args to virtualenv

- log.go
- stdlib.go
- stdlib.sh
Probably should use github.com/fatih/color
Broken, sorry, b/c I don't know how to integrate "go get" in Makefile
I'm not a go programmer. :(
See https://github.com/fatih/color/issues/50
Visit respectmyterm.com to learn why
Thanks!
> Only output color if $TERM is not dumb

- commands.go
- env.go
> add a configurable DIRENV_WARN_TIMEOUT option

- docs/sidebar.md
> mention emacs-direnv on website sidebar

- docs/sidebar.md
- man/direnv.toml.1
- man/direnv.toml.1.md
> Add manpage for config.toml

- man/direnv.toml.1.md
Fix a couple of issues highlighted by lintian when upgrading to 2.15.0.
> Fix lintian warnings

- .travis.yml
it seems like the releases stopped working
> WIP: .travis-ci.yml cleanup

- Makefile
- README.md
- man/direnv.1
- man/direnv.1.md
- shell.go
- shell_elvish.go
- test/direnv-test.elv
> direnv: add support for elvish

- README.md
Let's add some colors to this big block
> Add shell code highlight to example

- GNUmakefile
- README.md
- shell_fish.go
- test/direnv-test-common.sh
- test/direnv-test.fish
- test/direnv-test.tcsh
- test/direnv-test.zsh
- test/scenarios/missing-file-source-env/.envrc
splitting out all the awesome testing improvements from #464
> Better tests

- README.md
improve the readme for https://github.com/direnv/direnv/issues/249#issuecomment-465798846
> README: add note about auth

- cmd_export.go
- rc.go
- test/direnv-test-common.sh
make sure that nothing goes on stdout except the final direnv dump
fixes https://github.com/direnv/direnv/issues/224
> change the loading logic a bit

- stdlib.go
- stdlib.sh
> stdlib: fix source_env when the file doesn't exists

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
> Fix `source_up` docs to explain that search starts in parent directory 

- stdlib.go
- stdlib.sh
Adding to #505, this adds support for specifying multiple Python versions, e.g.:
```bash
layout pyenv 3.6.9 2.7.16
```
Pyenv supports specifying multiple pythons, e.g. `pyenv shell 3.6.9 2.7.16`, but `layout pyenv` didn't (till this PR). This also sets the PYENV_VERSION environment variable for multiple pythons as pyenv would (multiple versions separated by a colon, e.g. `3.6.9:2.7.16`).
This pretty much is just the previous layout_pyenv function run in a loop for each Python version specified.
The motivation for this was that I had Python 3 projects where I was using direnv to manage my Python 3 environment, but needed to run gcloud (Google Cloud SDK) which requires Python 2. 
Finally, this fixes a bug/edge case for virtualenv: previously, we were just invoking "virtualenv", which …
> layout_pyenv: support multiple python versions

- README.md
> Similar projects updated

- docs/installation.md
- install.sh
Curl installer is supposed to ease deployment by automating
all install steps.
@ssbarnea finally got around to finish your work :)
> adds experimental curl based installer

- cmd_apply_dump.go
- cmd_current.go
- cmd_dotenv.go
- cmd_dump.go
- cmd_edit.go
- cmd_export.go
- cmd_hook.go
- cmd_show_dump.go
- cmd_watch.go
- commands.go
- config.go
- env_diff.go
- file_times.go
- log.go
- rc.go
- script/both/main.go
- shell_vim.go
fix all the recommendations from staticcheck.io
> staticcheck

- rc.go
i think this works but im not a go person
> PS1 warning

- GNUmakefile
- README.md
- azure-pipelines.yml
- ci/build-steps.yml
- man/direnv.1
- man/direnv.1.md
- stdlib.go
- stdlib.sh
This will hopefully allow to create and share lib functions so that not
all of them have to be added to stdlib.sh
> stdlib: source files from .config/lib/*.sh

- cmd_dump.go
- cmd_exec.go
- cmd_export.go
- config.go
- env.go
- rc.go
- shell.nix
- shell_bash.go
- shell_zsh.go
- stdlib.go
- stdlib.sh
- test/direnv-test-common.sh
Finally trying to make the advertised Ctrl-C work
> Allow ctrl-c

- cmd_version.go
- go.mod
- go.sum
- man/direnv-stdlib.1.md
- stdlib.go
- stdlib.sh
- vendor/golang.org/x/mod/LICENSE
- vendor/golang.org/x/mod/PATENTS
- vendor/golang.org/x/mod/semver/semver.go
- vendor/modules.txt
Add a stdlib function to check that direnv is at least as old as the
desired version.
> direnv version <version_at_least>

- stdlib.go
- stdlib.sh
> stdlib: fix shellcheck warnings

- cmd_version.go
> direnv version: improve error message

- man/direnv.1.md
- stdlib.sh
- test/direnv-test.elv
These are issues in direnv sources that were encountered when packaging for debian. As they might affect other users as well, please consider merging.
> Fix issues caught during debian package update to v2.22.2

- cmd_allow.go
- cmd_deny.go
- cmd_edit.go
- cmd_exec.go
- cmd_export.go
- cmd_reload.go
- cmd_status.go
- config.go
- rc.go
Error handling tuples added to patch possible permissions issues into the terminal.
> Error handling tuples

- shell_fish.go
> Update shell_fish.go to use \X for UTF encoding

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
- man/direnv.toml.1
- stdlib.go
- stdlib.sh
- test/stdlib.bash
`stdlib`: new function `semver_search` that search a directory for the highest version on SemVer format. This function is factored out from the implementation of `use_node` with the intention to be used by other `use_*` implementations.
Edit: 2abfb8660dd1830b4364962dff41a957504efc7f is the commit to review, the others are just autogenerated changes.
> stdlib: semver_search

- stdlib.go
- stdlib.sh
> stdlib: adds GOPATH/bin to PATH

- stdlib.go
- stdlib.sh
Use pure bash implementations of basename and dirname from
https://github.com/bashup/realpaths to remove our dependency on
coreutils.
Should fix #692
> stdlib: add basename and dirname from realpath

- xdg/xdg.go
> Fix XDG_CACHE_HOME path

- stdlib.go
- stdlib.sh
Allow use of conda env by prefix (directory), as well as via name.
Resolves #716
> fix: layout anaconda <env_name_or_prefix>

- cmd_watch_dir.go
- commands.go
- stdlib.go
- stdlib.sh
- test/direnv-test-common.sh
- test/scenarios/watch-dir/.envrc
Adds a command named `watch_dir` that watches the directory passed to it
recursively
> add watch_dir command

- test/stdlib.bash
> fix: create temp dir in current working dir for one test

- shell_fish.go
> fixed fish shell hook to work with eval

- man/direnv.1
- man/direnv.1.md
Also fix some other references that ought to be to `$XDG_CONFIG_HOME` rather than `~/.config`.
> man/direnv.1.md: add FILES section (fix #758)

- shell_tcsh.go
- test/direnv-test.tcsh
- test/scenarios/parenthesis/.envrc
Thanks to @ytrinh for finding the solution!
Fixes #769
> tcsh: fix variable escaping

- man/direnv-stdlib.1
- man/direnv-stdlib.1.md
> Add docs about pipenv

- stdlib.sh
The code was rm'ing tmpfile instead of $tmpfile
> stdlib.sh: Fix removal of temp file

- man/direnv.toml.1
- man/direnv.toml.1.md
Fixes #605 
Signed-off-by: Mario Vejlupek <mario@vejlupek.cz>
> docs(direnv.toml) Add config.toml clarification

- .github/workflows/nix.yml
- .golangci.yml
- cmd_exec.go
- default.nix
- nix/sources.json
- nix/sources.nix
- stdlib.go
- stdlib.sh
- test/stdlib.bash
And fix related linting changes
> nix: bump nixpkgs

- install.sh
Treat `mingw*` as Windows (direnv/direnv#918)
> Treat mingw* as Windows OS

- install.sh
This PR tries to add more information about `bin_path` variable.
> add: information about bin_path

- install.sh
> install.sh: can specify direnv version

- .gitignore
- Brewfile
- README.md
... and add a Brewfile to help install dev dependencies
> doc: show how to run tests

- .mergify.yml
This configuration will automerge dependabot/renovate updates if CI succeeds.
> add mergify configuration

- .github/workflows/update-vendor-hash.yml
- default.nix
- script/update-vendor-hash
I splitted of the nixpkgs bump into it's own PR: https://github.com/direnv/direnv/pull/1146 so it can be reviewed first.
> Automatically update dependabot vendor hashes

- test/direnv-test.tcsh
> fix: quote tcsh $PATH, to avoid failure on whitespace

- internal/cmd/cmd_status.go
Was mentioned twice:
- https://github.com/direnv/direnv/issues/244#issuecomment-520487528
- https://github.com/direnv/direnv/issues/520#issuecomment-532892797
It will be used here:
https://github.com/srid/nix-health/issues/4
I have very little exposure working with GO, please correct me if I am wrong anywhere.
> `direnv status --json`

- internal/cmd/config.go
- internal/cmd/rc.go
> `allowPath` for `LoadedRC`

- README.md
Update description about autoenv.
> readme: Update autoenv section

- GNUmakefile
- flake.lock
- flake.nix
- internal/cmd/cmd_watch_print.go
- internal/cmd/commands.go
- test/direnv-test-common.sh
We need this in nix-direnv so we don't need to override watch_file or interpret the contents of DIRENV_WATCHES: https://github.com/nix-community/nix-direnv/pull/414
Might be also useful for debugging or tests.
> Add watch print command

- docs/installation.md
Use the Guru project which is official and well maintained.
- [go overlay](https://github.com/Dr-Terrible/go-overlay/tree/master/dev-util/direnv) - version 2.21.2
- [Guru](https://gitweb.gentoo.org/repo/proj/guru.git/tree/app-shells/direnv) - version 2.32.3
> Update installation.md for Gentoo

- internal/cmd/commands.go
- internal/cmd/config.go
- internal/cmd/const.go
- internal/cmd/shell_bash.go
- man/direnv.toml.1.md
Set zero or less to disable warn timeouts.
Fixes #1084
> feat: allow to disable warn timeouts

- internal/cmd/shell.go
- internal/cmd/shell_systemd.go
- internal/cmd/shell_systemd_test.go
- internal/cmd/shell_test.go
Basic example of a fix for #1225.
> Added a new `systemd` "shell" for export

- README.md
noticed that the link was missing, so I added it ^^
> Added fetchurl manpage link to README.md

- GNUmakefile
- README.md
- docs/hook.md
- internal/cmd/shell.go
- internal/cmd/shell_murex.go
- man/direnv.1
- man/direnv.1.md
- shell.nix
- test/direnv-test.mx
Added support for the [Murex](https://github.com/lmorg/murex) shell, and implemented `direnv-test-common.sh` as a Murex script.
> Add Murex support

- docs/hook.md
File moved in upstream repo in nushell/nu_scripts#650 and nushell/nu_scripts#700
> ✏️ Fix broken link

- internal/cmd/cmd_edit.go
- internal/cmd/cmd_export.go
- internal/cmd/cmd_log.go
- internal/cmd/commands.go
- internal/cmd/config.go
- internal/cmd/log.go
- internal/cmd/mod.go
- man/direnv.toml.1
- man/direnv.toml.1.md
- stdlib.sh
Allows you to filter the log messages that are outputted.
Should help with [this](https://github.com/direnv/direnv/issues/68)
> feat: logging filter

- stdlib.sh
> add support to fully reproducible guix shells

- stdlib.sh
Hello,
This enables wathing of Guix related files (`guix.scm` and `manifest.scm`).
References:
* `guix.scm`: [5.2 Invoking `guix package`](https://guix.gnu.org/manual/devel/en/html_node/Invoking-guix-package.html)
* `manifest.scm`: [7.1 Invoking `guix shell`](https://guix.gnu.org/manual/devel/en/html_node/Invoking-guix-shell.html)
Thank you
> stdlib: use_guix: Enable the watching of Guix related files.

- CHANGELOG.md
- internal/cmd/shell.go
- internal/cmd/shell_bash.go
- internal/cmd/shell_fish.go
- internal/cmd/shell_pwsh.go
- internal/cmd/shell_tcsh.go
- internal/cmd/shell_vim.go
This PR corrects grammar mistakes.
See https://dictionary.cambridge.org/dictionary/english/tilde
> fix typos in const, comments, and CHANGELOG

- internal/cmd/shell_bash.go
see https://github.com/ajeetdsouza/zoxide/blob/main/templates/bash.txt#L58
> Use PROMPT_COMMAND shortcut found in zoxide

- internal/cmd/shell_bash.go
> Revert "Use PROMPT_COMMAND shortcut found in zoxide"

- internal/cmd/log.go
> fix: accept true as valid DIRENV_DEBUG value

- internal/cmd/cmd_prune.go
> feat (prune): remove outdated hashes
